// test/features/progress/prg_test.dart
// PRG-01~04: Progress module — automated test suite
//
// PRG-T01~T10: ProgressDao unit tests (in-memory SQLite)
// PRG-T11~T16: ProgressDao query & calculation tests
// PRG-T17~T23: Resume dialog & countdown tests (fake_async)
// PRG-T24~T28: Clear progress tests (DAO + widget)

import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:fake_async/fake_async.dart';
import 'package:go_router/go_router.dart';
import 'package:just_audio/just_audio.dart';
import 'package:mockito/mockito.dart';
import 'package:nas_audio_player/core/contracts/database_contract.dart';
import 'package:nas_audio_player/core/database/dao/progress_dao.dart';
import 'package:nas_audio_player/features/player/player_screen.dart';
import 'package:nas_audio_player/shared/di/providers.dart';
import 'package:nas_audio_player/shared/models/connection_config.dart';
import 'package:nas_audio_player/shared/models/nas_file.dart';
import 'package:nas_audio_player/shared/models/play_progress.dart';
import 'package:nas_audio_player/shared/models/play_queue.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

import '../../helpers/fake_secure_storage.dart';
import '../../helpers/test_database.dart';
import '../../helpers/test_factories.dart';
import '../../helpers/mock_audio_player.dart';
import '../../helpers/widget_helpers.dart';

// ── Helpers ───────────────────────────────────────────────────────────────────

// testProgress() is imported from test_factories.dart as testProgress().

/// Compare two [PlayProgress] records, ignoring the `id` and `lastPlayedAt`
/// fields (which are generated by the DB).
void expectProgressEquals(
  PlayProgress actual,
  PlayProgress expected, {
  bool checkLastPlayedAt = false,
}) {
  expect(actual.connectionId, equals(expected.connectionId),
      reason: 'connectionId should match');
  expect(actual.filePath, equals(expected.filePath),
      reason: 'filePath should match');
  expect(actual.positionMs, equals(expected.positionMs),
      reason: 'positionMs should match');
  expect(actual.durationMs, equals(expected.durationMs),
      reason: 'durationMs should match');
  if (checkLastPlayedAt) {
    expect(actual.lastPlayedAt, equals(expected.lastPlayedAt),
        reason: 'lastPlayedAt should match');
  }
}

// ── TEST-05 helpers: 叶子 fake DAO + BrowserScreen 装配 ───────────────────────
// （同 bug_12/brw09 项目标准：走真实生产链路 BrowserScreen → progressForFileProvider
// → ProgressService → ProgressDao，仅叶子 DAO 注入内存 fake——sqflite_ffi 的
// Future 在 testWidgets FakeAsync 区不完成，widget 测试经契约注入 fake。）

/// 叶子 fake：内存 store 的 ProgressDao，记录 find 调用参数。
class _RecordingProgressDao extends ProgressDao {
  _RecordingProgressDao([Map<String, PlayProgress>? records])
      : _store = records ?? {};

  final Map<String, PlayProgress> _store;
  final List<(int, String)> findCalls = [];

  static String _key(int connectionId, String filePath) =>
      '$connectionId:$filePath';

  @override
  Future<PlayProgress?> find(int connectionId, String filePath) async {
    findCalls.add((connectionId, filePath));
    return _store[_key(connectionId, filePath)];
  }

  @override
  Future<void> delete(int connectionId, String filePath) async {
    _store.remove(_key(connectionId, filePath));
  }
}

final _test05Conn = ConnectionConfig(
  id: 1,
  name: 'NAS',
  url: 'http://nas.example.com',
  username: 'admin',
  isActive: true,
  createdAt: DateTime(2026, 1, 1),
  updatedAt: DateTime(2026, 1, 1),
);

PlayProgress _test05Progress(String filePath, int positionMs) => PlayProgress(
      connectionId: 1,
      filePath: filePath,
      positionMs: positionMs,
      durationMs: 600000,
      lastPlayedAt: DateTime(2026, 7, 24),
    );

const _test05FileA = '/music/a.mp3';
const _test05FileB = '/music/b.mp3';

/// 目录含两个音频文件；a.mp3 有进度（83s = 1:23），b.mp3 无进度（由传入 dao 决定）。
Future<void> _pumpTest05Browser(
  WidgetTester tester, {
  required ProgressDao dao,
  List<Override> extraOverrides = const [],
}) async {
  await tester.pumpWidget(buildTestAppWithPlayerRoute(
    const Scaffold(body: BrowserScreen()),
    overrides: [
      directoryContentsProvider('/').overrideWith((ref) async => [
            testAudio('a.mp3', _test05FileA),
            testAudio('b.mp3', _test05FileB),
          ]),
      activeConnectionProvider.overrideWith((ref) async => _test05Conn),
      progressDaoProvider.overrideWithValue(dao),
      ...extraOverrides,
    ],
  ));
  await tester.pumpAndSettle();
  expect(find.text('a.mp3'), findsOneWidget, reason: '前置条件：文件列表已渲染');
}

// ═════════════════════════════════════════════════════════════════════════════
// Main test entry
// ═════════════════════════════════════════════════════════════════════════════

void main() {
  // ── DAO tests ──

  group('PRG-01 自动保存播放进度 (PRG-T01~T10)', () {
    late Database db;
    late ProgressDao dao;

    setUpAll(() {
      initSqfliteFfi();
    });

    setUp(() async {
      db = await openTestDatabase(TestSchema.progress);
      dao = ProgressDao();
      // FK 约束现对所有 schema 生效（BUG-16-S2）：progress 行须引用已存在的连接
      await seedConnection(db);
      await seedConnection(db, id: 2); // 跨连接隔离用例（PRG-T13 等）引用连接 2
    });

    tearDown(() async {
      await db.close();
    });

    // ── PRG-T01: Save new file progress ────────────────────────────────────

    test('PRG-T01: upsert creates a new progress record', () async {
      final result = await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 45000,
        durationMs: 240000,
      );

      expect(result, isTrue,
          reason: 'upsert should return true when a new record is inserted');

      // Verify record exists in DB
      final saved = await dao.find(1, '/music/song.mp3');
      expect(saved, isNotNull, reason: '数据库应存在该文件进度记录');
      expect(saved!.positionMs, equals(45000));
      expect(saved.durationMs, equals(240000));
      expect(saved.connectionId, equals(1));
      expect(saved.filePath, equals('/music/song.mp3'));

      // Only one record
      final count = await dao.count();
      expect(count, equals(1), reason: '新文件只有一条记录');
    });

    // ── PRG-T02: Same file second save (UPSERT) ────────────────────────────

    test('PRG-T02: second save updates existing record (UPSERT semantics)',
        () async {
      // First save
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 30000,
        durationMs: 120000,
      );

      // Second save at a later position
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 90000,
        durationMs: 120000,
      );

      // Verify: only ONE record (UPSERT, not duplicate)
      final count = await dao.count();
      expect(count, equals(1), reason: '同一(connectionId, filePath)应只有一条记录，非新增');

      // Position updated to the later value
      final saved = await dao.find(1, '/music/song.mp3');
      expect(saved, isNotNull);
      expect(saved!.positionMs, equals(90000),
          reason: 'position_ms 应更新为第二次保存的位置');
    });

    // ── PRG-T03: Position < 5s → not saved ─────────────────────────────────

    test('PRG-T03: position under 5 seconds is not persisted', () async {
      final result = await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 3000, // 3 seconds
        durationMs: 120000,
      );

      expect(result, isFalse, reason: '位置 < 5 秒时 upsert 应返回 false（skip）');

      // Verify no record was created
      final saved = await dao.find(1, '/music/song.mp3');
      expect(saved, isNull, reason: '位置 < 5 秒不应写入数据库');

      final count = await dao.count();
      expect(count, equals(0), reason: '不应有任何记录');
    });

    // ── PRG-T04: Position > duration - 10s → record cleared ────────────────

    test('PRG-T04: position near end clears the progress record', () async {
      // First save a record
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 30000,
        durationMs: 120000,
      );

      // Save with position > duration - 10s (i.e. > 110000 for 120s track)
      final result = await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 115000, // > 120000 - 10000 = 110000
        durationMs: 120000,
      );

      expect(result, isNull, reason: '位置 > 总时长 - 10s 时应返回 null（记录被清除）');

      // Verify record was deleted
      final saved = await dao.find(1, '/music/song.mp3');
      expect(saved, isNull, reason: '播完的文件进度记录应被删除');

      final count = await dao.count();
      expect(count, equals(0), reason: '表中不应有记录');
    });

    // ── PRG-T05: Position == 5s → should save (boundary) ───────────────────

    test('PRG-T05: position at exactly 5 seconds is saved', () async {
      final result = await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 5000, // exactly 5 seconds
        durationMs: 120000,
      );

      expect(result, isTrue, reason: '位置恰好 5 秒时应保存（>=5s 即保存）');

      final saved = await dao.find(1, '/music/song.mp3');
      expect(saved, isNotNull, reason: '数据库应有记录');
      expect(saved!.positionMs, equals(5000));
    });

    // ── PRG-T06: Position == duration - 10s → NOT cleared (boundary) ───────

    test('PRG-T06: position at exactly duration-10s is saved, not cleared',
        () async {
      // First save a record
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 5000,
        durationMs: 120000,
      );

      // Save with position == duration - 10s (i.e. 110000 for 120s track)
      final result = await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 110000, // == 120000 - 10000
        durationMs: 120000,
      );

      expect(result, isTrue, reason: '位置==总时长-10s 时应保存（> 才清除，= 不清除）');

      // Verify record still exists with updated position
      final saved = await dao.find(1, '/music/song.mp3');
      expect(saved, isNotNull, reason: '记录应仍存在');
      expect(saved!.positionMs, equals(110000));
    });

    // ── PRG-T07: Pause → save ──────────────────────────────────────────────

    test('PRG-T07: pause triggers position save', () async {
      // Simulate the "pause" trigger: upsert current position
      final result = await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 67300, // paused at 1:07.3
        durationMs: 180000,
      );

      expect(result, isTrue);
      final saved = await dao.find(1, '/music/song.mp3');
      expect(saved!.positionMs, equals(67300), reason: '暂停时应保存当前播放位置');
    });

    // ── PRG-T08: Track switch → save previous track ────────────────────────

    test('PRG-T08: track switch saves previous track progress', () async {
      // Play track A
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/track_a.mp3',
        positionMs: 45000,
        durationMs: 120000,
      );

      // Switch to track B — save track A's final position
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/track_a.mp3',
        positionMs: 80000,
        durationMs: 120000,
      );

      final savedA = await dao.find(1, '/music/track_a.mp3');
      expect(savedA!.positionMs, equals(80000), reason: '切换曲目时应保存上一首的最终进度');

      // Start playing track B
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/track_b.mp3',
        positionMs: 15000,
        durationMs: 180000,
      );

      final savedB = await dao.find(1, '/music/track_b.mp3');
      expect(savedB, isNotNull, reason: '新曲目的进度应正常保存');

      // Both tracks have independent records
      final count = await dao.count();
      expect(count, equals(2), reason: '两首曲目各有独立记录');
    });

    // ── PRG-T09: App background → save ─────────────────────────────────────

    test('PRG-T09: app entering background triggers save', () async {
      // Simulate background save triggered by AppLifecycleState.paused
      final result = await dao.upsert(
        connectionId: 1,
        filePath: '/music/audiobook.m4b',
        positionMs: 3600000, // 1 hour in
        durationMs: 14400000, // 4 hour book
      );

      expect(result, isTrue, reason: '应用进入后台时应保存当前进度');

      final saved = await dao.find(1, '/music/audiobook.m4b');
      expect(saved!.positionMs, equals(3600000), reason: '后台保存的进度应准确');
    });

    // ── PRG-T10: App close (detached) → save ───────────────────────────────

    test('PRG-T10: app detached lifecycle triggers save', () async {
      // Simulate save triggered by AppLifecycleState.detached
      final result = await dao.upsert(
        connectionId: 1,
        filePath: '/music/podcast.mp3',
        positionMs: 1234000,
        durationMs: 1800000,
      );

      expect(result, isTrue, reason: '应用关闭时应保存当前进度');

      final saved = await dao.find(1, '/music/podcast.mp3');
      expect(saved, isNotNull, reason: '关闭时的进度不应丢失');
      expect(saved!.positionMs, equals(1234000));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // PRG-02: Query & calculation tests
  // ═══════════════════════════════════════════════════════════════════════════

  group('PRG-02 启动时恢复播放进度 (PRG-T11~T16)', () {
    late Database db;
    late ProgressDao dao;

    setUpAll(() {
      initSqfliteFfi();
    });

    setUp(() async {
      db = await openTestDatabase(TestSchema.progress);
      dao = ProgressDao();
      // FK 约束现对所有 schema 生效（BUG-16-S2）：progress 行须引用已存在的连接
      await seedConnection(db);
      await seedConnection(db, id: 2); // 跨连接隔离用例（PRG-T13 等）引用连接 2
    });

    tearDown(() async {
      await db.close();
    });

    // ── PRG-T11: Query file with saved progress ────────────────────────────

    test('PRG-T11: find returns correct PlayProgress for saved file', () async {
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/song.mp3',
        positionMs: 75400, // 1:15.4
        durationMs: 200000,
      );

      final result = await dao.find(1, '/music/song.mp3');
      expect(result, isNotNull, reason: '有进度记录的文件应返回 PlayProgress');
      expect(result!.positionMs, equals(75400),
          reason: '查询到的 position 应与保存值一致');
      expect(result.durationMs, equals(200000));
      expect(result.filePath, equals('/music/song.mp3'));
      expect(result.connectionId, equals(1));
    });

    // ── PRG-T12: Query file without progress ───────────────────────────────

    test('PRG-T12: find returns null for file with no saved progress',
        () async {
      final result = await dao.find(1, '/music/never_played.mp3');
      expect(result, isNull, reason: '无进度记录的文件应返回 null');
    });

    // ── PRG-T13: Different connectionId, same path → independent ───────────

    test('PRG-T13: progress is independent per connection', () async {
      // Save progress for connection 1
      await dao.upsert(
        connectionId: 1,
        filePath: '/shared/music.mp3',
        positionMs: 30000,
        durationMs: 120000,
      );

      // Save progress for connection 2, same file path
      await dao.upsert(
        connectionId: 2,
        filePath: '/shared/music.mp3',
        positionMs: 90000,
        durationMs: 120000,
      );

      // Query connection 1
      final conn1Progress = await dao.find(1, '/shared/music.mp3');
      expect(conn1Progress, isNotNull);
      expect(conn1Progress!.positionMs, equals(30000),
          reason: '连接 1 的进度不受连接 2 影响');

      // Query connection 2
      final conn2Progress = await dao.find(2, '/shared/music.mp3');
      expect(conn2Progress, isNotNull);
      expect(conn2Progress!.positionMs, equals(90000), reason: '连接 2 的进度应独立记录');

      // Two records total
      final count = await dao.count();
      expect(count, equals(2), reason: '不同连接的同路径文件应有两条独立记录');
    });

    // ── PRG-T14: percentage with valid duration ────────────────────────────

    test('PRG-T14: percentage is 0.25 when position=30s, duration=120s', () {
      // positionMs = 30000, durationMs = 120000
      final progress = testProgress(positionMs: 30000, durationMs: 120000);
      expect(progress.percentage, equals(0.25), reason: '30/120 = 0.25');
    });

    // ── PRG-T15: percentage when duration is null → 0 ──────────────────────

    test('PRG-T15: percentage returns 0 when duration is null', () {
      final progress = testProgress(
        positionMs: 50000,
        durationMs: null,
      );
      expect(progress.percentage, equals(0.0),
          reason: 'duration 为 null 时 percentage 应返回 0，不崩溃');
    });

    // ── PRG-T16: getRecentlyPlayed ordered by last_played_at DESC ──────────

    test('PRG-T16: getRecentlyPlayed returns ordered, limited list', () async {
      // Insert 5 records with explicit timestamps
      for (int i = 1; i <= 5; i++) {
        final lastPlayed = DateTime(2024, 1, 15, 10, i); // incrementing
        final progress = testProgress(
          connectionId: 1,
          filePath: '/music/track_$i.mp3',
          positionMs: i * 10000,
          lastPlayedAt: lastPlayed,
        );
        // Use raw insert for timestamp control (upsert uses DateTime.now())
        // REF-02-S9: rawInsert 移出契约，测试播种改 rawInsertForTest（helpers）
        await dao.rawInsertForTest(progress);
      }

      // Get recently played with default limit (20)
      final all = await dao.getRecentlyPlayed();
      expect(all.length, equals(5), reason: '应返回全部 5 条记录');

      // Ordered by last_played_at DESC (most recent first)
      for (int i = 1; i < all.length; i++) {
        expect(
          all[i]
              .lastPlayedAt
              .millisecondsSinceEpoch
              .compareTo(all[i - 1].lastPlayedAt.millisecondsSinceEpoch),
          lessThanOrEqualTo(0),
          reason: '应按 last_played_at 降序排列',
        );
      }
      // Most recent (track 5) should be first
      expect(all.first.filePath, equals('/music/track_5.mp3'));

      // Test limit
      final limited = await dao.getRecentlyPlayed(limit: 3);
      expect(limited.length, equals(3), reason: '应只返回 limit 条记录');
      expect(limited.first.filePath, equals('/music/track_5.mp3'));
      expect(limited.last.filePath, equals('/music/track_3.mp3'));
    });

    test('latestPlayedProgressProvider returns the most recent record',
        () async {
      await dao.rawInsertForTest(
        testProgress(
          connectionId: 1,
          filePath: '/music/older.mp3',
          positionMs: 10000,
          lastPlayedAt: DateTime(2026, 5, 17, 9, 0),
        ),
      );
      await dao.rawInsertForTest(
        testProgress(
          connectionId: 1,
          filePath: '/music/latest.mp3',
          positionMs: 55000,
          lastPlayedAt: DateTime(2026, 5, 17, 10, 0),
        ),
      );

      final container = ProviderContainer(
        overrides: [
          progressDaoProvider.overrideWithValue(dao),
        ],
      );
      addTearDown(container.dispose);

      final latest = await container.read(latestPlayedProgressProvider.future);
      expect(latest, isNotNull);
      expect(latest!.filePath, equals('/music/latest.mp3'));
      expect(latest.positionMs, equals(55000));
    });

    test('latestPlayedProgressProvider returns null when history is empty',
        () async {
      final container = ProviderContainer(
        overrides: [
          progressDaoProvider.overrideWithValue(dao),
        ],
      );
      addTearDown(container.dispose);

      final latest = await container.read(latestPlayedProgressProvider.future);
      expect(latest, isNull);
    });

    // BUG-11（2026-07-24 用户裁决：按文件多记录模型）：
    // 原 'findLatest prunes legacy multi-row history' 与
    // 'upsertLatest replaces previous active progress record' 两条用例锚定
    // 已废弃的单活跃记录模型（findLatest 读前物理剪枝 / upsertLatest 全表替换），
    // 改为锚定纯查询语义——findLatest 返回最近一条且不得删除其它文件进度。
    test('findLatest is a pure query: latest record, no deletion side effect',
        () async {
      await dao.rawInsertForTest(
        testProgress(
          connectionId: 1,
          filePath: '/music/older.mp3',
          positionMs: 15000,
          lastPlayedAt: DateTime(2026, 5, 17, 8, 0),
        ),
      );
      await dao.rawInsertForTest(
        testProgress(
          connectionId: 2,
          filePath: '/music/newer.mp3',
          positionMs: 45000,
          lastPlayedAt: DateTime(2026, 5, 17, 9, 0),
        ),
      );

      final latest = await dao.findLatest();
      expect(latest, isNotNull);
      expect(latest!.filePath, equals('/music/newer.mp3'));
      expect(await dao.count(), equals(2),
          reason: '按文件多记录模型：findLatest 是纯查询，不得删除其它记录');
      expect(await dao.find(1, '/music/older.mp3'), isNotNull,
          reason: '历史文件进度必须在 findLatest 后存活（BUG-11 回归锚点）');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // PRG-03: Resume dialog & countdown tests
  // ═══════════════════════════════════════════════════════════════════════════

  group('PRG-03 进度恢复确认提示 (PRG-T17~T23)', () {
    // ── PRG-T17: Dialog shows formatted progress time ──────────────────────

    testWidgets('PRG-T17: dialog displays progress in HH:MM:SS format',
        (WidgetTester tester) async {
      final progress = testProgress(
        positionMs: 5025000, // 1:23:45
        durationMs: 7200000,
      );

      await tester.pumpWidget(
        ProviderScope(
          child: MaterialApp(
            home: Scaffold(
              body: Builder(
                builder: (context) {
                  return ElevatedButton(
                    onPressed: () {
                      showProgressResumeDialog(
                        context,
                        ProviderScope.containerOf(context),
                        progress,
                      );
                    },
                    child: const Text('Show Dialog'),
                  );
                },
              ),
            ),
          ),
        ),
      );

      await tester.tap(find.text('Show Dialog'));
      await tester.pumpAndSettle();

      // Dialog title
      expect(find.text('恢复播放进度'), findsOneWidget, reason: '应显示对话框标题');

      // Position formatted: 1:23:45
      expect(find.textContaining('1:23:45'), findsOneWidget,
          reason: '对话框应显示保存的进度时间 HH:MM:SS');

      // Question text
      expect(find.text('是否从此处继续？'), findsOneWidget, reason: '应显示确认提示文字');

      // Two action buttons
      expect(find.text('从头播放'), findsOneWidget, reason: '应有从头播放按钮');
      expect(find.textContaining('继续播放'), findsWidgets,
          reason: '应有继续播放按钮（含倒计时）');
    });

    // ── PRG-T18 / TEST-05-S1: No progress → direct play, no dialog ─────────

    testWidgets('TEST-05-S1: 无进度文件点击 → 直接播放、无弹窗', (WidgetTester tester) async {
      // 空 DB：没有任何进度记录。真实 BrowserScreen + 生产链路
      // （onFileTap → progressForFileProvider → DAO），仅叶子 DAO 注入 fake。
      final dao = _RecordingProgressDao();
      await _pumpTest05Browser(tester, dao: dao);

      // 容器须在导航前获取（点击后 BrowserScreen 出栈，element 不可再查）
      final container =
          ProviderScope.containerOf(tester.element(find.byType(BrowserScreen)));

      // When 用户点击无进度文件 b.mp3
      await tester.tap(find.text('b.mp3'));
      await tester.pumpAndSettle();

      // Then 直接触发播放（等价触发：进入播放页）
      expect(find.text('Player'), findsOneWidget,
          reason: 'TEST-05-S1: 点击无进度文件应直接进入播放页');

      // 否定断言: 不弹出 showProgressResumeDialog（无进度时无对话框）
      expect(find.text('恢复播放进度'), findsNothing,
          reason: 'TEST-05-S1: 无进度文件点击不得弹出恢复播放进度对话框');

      // 否定断言: 不修改播放队列中其他曲目的状态——队列当前曲目为被点击文件，
      // 且不携带恢复位置（无进度 → 从头播放）
      final queue = container.read(currentPlayQueueProvider);
      expect(queue, isNotNull, reason: 'TEST-05-S1: 点击后应建立播放队列');
      expect(queue!.current.path, equals(_test05FileB),
          reason: 'TEST-05-S1: 队列当前曲目应为被点击的文件 b.mp3');
      expect(queue.startPositionMs, isNull,
          reason: 'TEST-05-S1: 无进度时队列不得携带恢复位置');

      // 实际生产行为锚定（spec 原否定"不查询 progressDao"与生产不符——
      // onFileTap 经 progressForFileProvider 直读 DAO 一次做弹窗决策，
      // 与 spec §4 TEST-05-INV1 自身证据一致）：
      // 仅对被点击文件查询一次，不做任何其他查询。
      expect(dao.findCalls, [(1, _test05FileB)],
          reason: 'TEST-05-S1: 点击仅查询被点击文件一次（弹窗决策用），'
              '无预渲染查询、无其他文件查询');
    });

    testWidgets('TEST-05-S1: 无进度文件点击 → loadAndPlay 触发一次（真实 PlayerScreen 装配）',
        (WidgetTester tester) async {
      // brw11 模式：/player 挂真实 PlayerScreen（其初始化经 loadAndPlayProvider
      // 加载音频），锚定"直接触发播放（IAudioPlayer.load + play）"。
      final mockPlayer = MockAudioPlayer();
      when(mockPlayer.playing).thenReturn(true);
      when(mockPlayer.processingState).thenReturn(ProcessingState.ready);
      when(mockPlayer.processingStateStream)
          .thenAnswer((_) => const Stream<ProcessingState>.empty());
      when(mockPlayer.playingStream)
          .thenAnswer((_) => Stream<bool>.value(true));
      when(mockPlayer.sequenceState).thenReturn(null);
      when(mockPlayer.duration).thenReturn(const Duration(minutes: 4));
      when(mockPlayer.position).thenReturn(Duration.zero);
      when(mockPlayer.playerStateStream).thenAnswer(
          (_) => Stream.value(PlayerState(false, ProcessingState.ready)));
      when(mockPlayer.speedStream).thenAnswer((_) => Stream.value(1.0));

      int loadAndPlayCalls = 0;

      final router = GoRouter(
        initialLocation: '/',
        routes: [
          GoRoute(
            path: '/',
            builder: (_, __) => const Scaffold(body: BrowserScreen()),
          ),
          GoRoute(
            path: '/player',
            builder: (_, __) => const PlayerScreen(),
          ),
        ],
      );

      await tester.pumpWidget(
        ProviderScope(
          overrides: [
            directoryContentsProvider('/').overrideWith((ref) async => [
                  testAudio('a.mp3', _test05FileA),
                  testAudio('b.mp3', _test05FileB),
                ]),
            activeConnectionProvider.overrideWith((ref) async => _test05Conn),
            audioPlayerProvider.overrideWithValue(mockPlayer),
            audioHandlerProvider.overrideWith((ref) => null),
            playModeProvider.overrideWith((ref) => PlayMode.sequential),
            seekStepSettingProvider.overrideWith((ref) => 15),
            loadAndPlayProvider.overrideWithValue(() async {
              loadAndPlayCalls++;
              return const TrackLoadResult.loaded();
            }),
            progressDaoProvider.overrideWithValue(_RecordingProgressDao()),
            secureStorageProvider.overrideWithValue(
                FakeSecureStorage()..setPassword(1, 'secret')),
          ],
          child: MaterialApp.router(routerConfig: router),
        ),
      );
      await tester.pumpAndSettle();
      expect(find.text('b.mp3'), findsOneWidget, reason: '前置条件：文件列表已渲染');

      // 预热 activeConnection（同 brw11：PlayerScreen 的 _runSerializedLoad
      // 需 valueOrNull 非空；在同一个容器内读，避免跨 scope override 不匹配）
      final container =
          ProviderScope.containerOf(tester.element(find.byType(BrowserScreen)));
      await container.read(activeConnectionProvider.future);
      await tester.pump();
      await tester.pumpAndSettle();

      // When 用户点击无进度文件 b.mp3
      await tester.tap(find.text('b.mp3'));
      await tester.pumpAndSettle();

      // Then 直接触发播放：loadAndPlay 恰好被调一次 + 播放页挂载
      expect(loadAndPlayCalls, equals(1),
          reason: 'TEST-05-S1: 无进度文件点击应直接触发 loadAndPlay 播放');
      expect(find.byType(PlayerScreen), findsOneWidget,
          reason: 'TEST-05-S1: 点击无进度文件应进入播放页');

      // 否定断言: 无进度时不弹出恢复对话框
      expect(find.text('恢复播放进度'), findsNothing,
          reason: 'TEST-05-S1: 无进度文件点击不得弹出恢复播放进度对话框');
    });

    // ── PRG-T19: "继续播放" → seek to saved position ──────────────────────

    testWidgets('PRG-T19: clicking continue resumes from saved position',
        (WidgetTester tester) async {
      bool? continueSelected;

      final progress = testProgress(positionMs: 180000); // 3:00

      await tester.pumpWidget(
        ProviderScope(
          child: MaterialApp(
            home: Scaffold(
              body: Builder(
                builder: (context) {
                  return ElevatedButton(
                    onPressed: () async {
                      continueSelected = await showProgressResumeDialog(
                        context,
                        ProviderScope.containerOf(context),
                        progress,
                      );
                    },
                    child: const Text('Show Dialog'),
                  );
                },
              ),
            ),
          ),
        ),
      );

      await tester.tap(find.text('Show Dialog'));
      await tester.pumpAndSettle();

      // Click "继续播放" button (the one with countdown text)
      await tester.tap(find.textContaining('继续播放'));
      await tester.pumpAndSettle();

      expect(continueSelected, isTrue, reason: '点击继续播放应返回 true');
    });

    // ── PRG-T20: "从头播放" → start from 0, delete progress ───────────────

    testWidgets('PRG-T20: clicking start over returns false',
        (WidgetTester tester) async {
      bool? startOverSelected;

      final progress = testProgress(positionMs: 30000);

      await tester.pumpWidget(
        ProviderScope(
          child: MaterialApp(
            home: Scaffold(
              body: Builder(
                builder: (context) {
                  return ElevatedButton(
                    onPressed: () async {
                      startOverSelected = await showProgressResumeDialog(
                        context,
                        ProviderScope.containerOf(context),
                        progress,
                      );
                    },
                    child: const Text('Show Dialog'),
                  );
                },
              ),
            ),
          ),
        ),
      );

      await tester.tap(find.text('Show Dialog'));
      await tester.pumpAndSettle();

      // Click "从头播放" button
      await tester.tap(find.text('从头播放'));
      await tester.pumpAndSettle();

      expect(startOverSelected, isFalse, reason: '点击从头播放应返回 false');
    });

    // ── PRG-T21: 5-second timeout auto-selects "继续播放" ──────────────────

    test('PRG-T21: 5-second countdown auto-selects continue', () {
      fakeAsync((async) {
        final container = ProviderContainer();
        addTearDown(container.dispose);

        final notifier = container.read(progressResumeProvider.notifier);
        final progress = testProgress(positionMs: 60000);

        // Show the dialog (starts countdown at 5)
        notifier.show(progress);

        // Verify initial state
        expect(notifier.state, isNotNull);
        expect(notifier.state!.countdownSeconds, equals(5),
            reason: '初始倒计时应为 5');

        // The Timer fires each time we elapse 1 second
        async.elapse(const Duration(seconds: 1));
        expect(notifier.state!.countdownSeconds, equals(4),
            reason: '经过 1 秒后倒计时应为 4');

        async.elapse(const Duration(seconds: 1));
        expect(notifier.state!.countdownSeconds, equals(3),
            reason: '经过 2 秒后倒计时应为 3');

        async.elapse(const Duration(seconds: 1));
        expect(notifier.state!.countdownSeconds, equals(2),
            reason: '经过 3 秒后倒计时应为 2');

        async.elapse(const Duration(seconds: 1));
        expect(notifier.state!.countdownSeconds, equals(1),
            reason: '经过 4 秒后倒计时应为 1');

        async.elapse(const Duration(seconds: 1));
        expect(notifier.state!.countdownSeconds, equals(0),
            reason: '经过 5 秒后倒计时应为 0');
        expect(notifier.state!.isExpired, isTrue,
            reason: '倒计时归零后 isExpired 应为 true');

        container.dispose();
      });
    });

    // ── PRG-T22: Countdown display on button ───────────────────────────────

    testWidgets('PRG-T22: button shows countdown like "继续播放 (4)"',
        (WidgetTester tester) async {
      final progress = testProgress(positionMs: 30000);

      await tester.pumpWidget(
        ProviderScope(
          child: MaterialApp(
            home: Scaffold(
              body: Builder(
                builder: (context) {
                  return ElevatedButton(
                    onPressed: () async {
                      await showProgressResumeDialog(
                        context,
                        ProviderScope.containerOf(context),
                        progress,
                      );
                    },
                    child: const Text('Show Dialog'),
                  );
                },
              ),
            ),
          ),
        ),
      );

      await tester.tap(find.text('Show Dialog'));
      // pump only (not pumpAndSettle) so the periodic timer is pending
      await tester.pump();

      // Initial state: "继续播放 (5)"
      expect(find.text('继续播放 (5)'), findsOneWidget, reason: '初始应显示 "继续播放 (5)"');

      // Advance 1 second
      await tester.pump(const Duration(seconds: 1));
      expect(find.text('继续播放 (4)'), findsOneWidget,
          reason: '1 秒后应显示 "继续播放 (4)"');

      // Advance another second
      await tester.pump(const Duration(seconds: 1));
      expect(find.text('继续播放 (3)'), findsOneWidget,
          reason: '2 秒后应显示 "继续播放 (3)"');
    });

    // ── PRG-T23: Dialog time matches progress record ──────────────────────

    test('PRG-T23: formatted time in dialog matches PlayProgress.position', () {
      final progress1 = testProgress(positionMs: 90000); // 1:30
      expect(progress1.formattedPosition, equals('1:30'));

      final progress2 = testProgress(positionMs: 3725000); // 1:02:05
      expect(progress2.formattedPosition, equals('1:02:05'));

      final progress3 = testProgress(positionMs: 0); // 0:00
      expect(progress3.formattedPosition, equals('0:00'));

      // The dialog displays progress.formattedPosition,
      // so the dialog time == PlayProgress.position formatted.
      // Verified by widget test PRG-T17 showing "1:23:45".
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // PRG-04: Clear progress tests
  // ═══════════════════════════════════════════════════════════════════════════

  group('PRG-04 清除单个文件进度 (PRG-T24~T28)', () {
    late Database db;
    late ProgressDao dao;

    setUpAll(() {
      initSqfliteFfi();
    });

    setUp(() async {
      db = await openTestDatabase(TestSchema.progress);
      dao = ProgressDao();
      // FK 约束现对所有 schema 生效（BUG-16-S2）：progress 行须引用已存在的连接
      await seedConnection(db);
      await seedConnection(db, id: 2); // 跨连接隔离用例（PRG-T13 等）引用连接 2
    });

    tearDown(() async {
      await db.close();
    });

    // ── PRG-T24 / TEST-05-S2: Long-press file WITH progress → real menu ────
    //
    // 断言真实 widget 的菜单项（生产 BrowserScreen 构建），
    // 不再在测试内重建 menuItems 逻辑（旧 PRG8 问题）。
    // 生产菜单实测含：文件名（菜单标题）+ "清除播放进度" + "已保存进度 HH:MM:SS"；
    // spec 的"And 菜单项包含'添加到队列'/'查看文件信息'"与生产不符（见报告）。

    testWidgets('TEST-05-S2: 有进度文件长按 → 真实菜单含"清除播放进度"',
        (WidgetTester tester) async {
      final dao = _RecordingProgressDao({
        '1:$_test05FileA': _test05Progress(_test05FileA, 83000),
      });
      await _pumpTest05Browser(tester, dao: dao);

      // When 长按有进度的文件 a.mp3 触发上下文菜单
      await tester.longPress(find.text('a.mp3'));
      await tester.pumpAndSettle();

      // Then 真实 widget 菜单项包含"清除播放进度"
      expect(find.text('清除播放进度'), findsOneWidget,
          reason: 'TEST-05-S2: 有进度文件长按菜单应包含"清除播放进度"');

      // And 菜单标题为被长按的文件名（tile 一个 + 菜单标题一个）
      expect(find.text('a.mp3'), findsNWidgets(2),
          reason: 'TEST-05-S2: 长按菜单应包含被长按文件的名字作为菜单标题');

      // And 菜单项包含已保存进度信息（生产真实菜单项，非测试重建）
      expect(find.text('已保存进度 1:23'), findsOneWidget,
          reason: 'TEST-05-S2: 长按菜单应包含"已保存进度"信息项');
    });

    // ── PRG-T25 / TEST-05-S3: Long-press WITHOUT progress → no clear item ──
    //
    // 生产行为实测：无进度文件 onFileLongPress 早退 → 整个上下文菜单不弹出
    // （spec 期望的"菜单仅含'添加到队列'/'查看文件信息'"与生产不符，见报告）。
    // 核心否定断言（不出现"清除播放进度"）在生产与 spec 下均成立。

    testWidgets('TEST-05-S3: 无进度文件长按 → 不出现"清除播放进度"（生产行为：整菜单不弹出）',
        (WidgetTester tester) async {
      // a.mp3 有进度（对照组），b.mp3 无进度
      final dao = _RecordingProgressDao({
        '1:$_test05FileA': _test05Progress(_test05FileA, 83000),
      });
      await _pumpTest05Browser(tester, dao: dao);

      // When 长按无进度的文件 b.mp3 触发上下文菜单
      await tester.longPress(find.text('b.mp3'));
      await tester.pumpAndSettle();

      // Then 菜单不包含"清除播放进度"
      expect(find.text('清除播放进度'), findsNothing,
          reason: 'TEST-05-S3: 无进度文件长按不得出现"清除播放进度"'
              '（progress == null 早退分支）');

      // 否定断言（生产行为）: 无进度文件整菜单不弹出——spec 假设的
      // "添加到队列"/"查看文件信息"基础项在生产中并不渲染
      expect(find.text('添加到队列'), findsNothing,
          reason: 'TEST-05-S3: 无进度文件长按不弹出任何菜单（无"添加到队列"项）');
      expect(find.text('查看文件信息'), findsNothing,
          reason: 'TEST-05-S3: 无进度文件长按不弹出任何菜单（无"查看文件信息"项）');
      expect(find.textContaining('已保存进度'), findsNothing,
          reason: 'TEST-05-S3: 无进度文件长按不弹出任何菜单（无进度信息项）');

      // 否定断言: 长按不得触发 onTap 的播放/导航
      expect(find.text('Player'), findsNothing,
          reason: 'TEST-05-S3: 长按无进度文件不得触发播放导航');

      // 对照组: 同一页面内长按有进度文件仍正常弹菜单（证明上述结果是
      // 无进度分支所致，而非菜单整体失效）
      await tester.longPress(find.text('a.mp3'));
      await tester.pumpAndSettle();
      expect(find.text('清除播放进度'), findsOneWidget,
          reason: 'TEST-05-S3 对照: 有进度文件长按仍应弹出含"清除播放进度"的菜单');
    });

    // ── PRG-T26: Click "清除播放进度" → delete from DB ─────────────────────

    test('PRG-T26: clearing progress removes the record from database',
        () async {
      // First save progress
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/to_clear.mp3',
        positionMs: 120000,
        durationMs: 300000,
      );

      // Verify it exists
      expect(await dao.find(1, '/music/to_clear.mp3'), isNotNull);

      // Simulate "清除播放进度" action
      await dao.delete(1, '/music/to_clear.mp3');

      // Verify record is gone
      final afterDelete = await dao.find(1, '/music/to_clear.mp3');
      expect(afterDelete, isNull, reason: '清除后数据库中不应再有该文件的进度记录');

      final count = await dao.count();
      expect(count, equals(0), reason: '表中不应有记录');
    });

    // ── PRG-T27: After clear → progress bar disappears ─────────────────────

    test('PRG-T27: progress indicator becomes null after clearing record',
        () async {
      // Logic verification: after delete, find() returns null,
      // so the UI's progressCheck becomes null and the progress bar hides.
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/visible.mp3',
        positionMs: 60000,
        durationMs: 240000,
      );

      // Before clear: progress exists → progress bar visible
      final before = await dao.find(1, '/music/visible.mp3');
      expect(before, isNotNull, reason: '清除前进度记录存在 → 进度条应显示');

      // Clear
      await dao.delete(1, '/music/visible.mp3');

      // After clear: progress gone → progress bar hidden
      final after = await dao.find(1, '/music/visible.mp3');
      expect(after, isNull, reason: '清除后进度记录不存在 → 进度条应消失');
    });

    // ── PRG-T28: deleteProgress method directly ────────────────────────────

    test('PRG-T28: delete method removes specific record from database',
        () async {
      // Save records for multiple files
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/keep.mp3',
        positionMs: 30000,
        durationMs: 200000,
      );
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/remove.mp3',
        positionMs: 90000,
        durationMs: 200000,
      );
      await dao.upsert(
        connectionId: 2,
        filePath: '/music/remove.mp3',
        positionMs: 45000,
        durationMs: 200000,
      );

      expect(await dao.count(), equals(3), reason: '初始应有 3 条记录');

      // Delete only one specific record
      await dao.delete(1, '/music/remove.mp3');

      // Verify: only the targeted record is gone
      expect(await dao.find(1, '/music/remove.mp3'), isNull,
          reason: '被删除的指定记录应不存在');

      // Other records unaffected
      expect(await dao.find(1, '/music/keep.mp3'), isNotNull,
          reason: '其他文件记录不应受影响');
      expect(await dao.find(2, '/music/remove.mp3'), isNotNull,
          reason: '其他连接的记录不应受影响');

      expect(await dao.count(), equals(2), reason: '删除后应剩 2 条记录');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Additional: shouldSave / shouldClear static method tests
  // ═══════════════════════════════════════════════════════════════════════════

  group('ProgressDao static helpers', () {
    test('shouldSave returns true for positionms >= 5000', () {
      expect(ProgressDao.shouldSave(4999), isFalse);
      expect(ProgressDao.shouldSave(5000), isTrue);
      expect(ProgressDao.shouldSave(5001), isTrue);
      expect(ProgressDao.shouldSave(0), isFalse);
      expect(ProgressDao.shouldSave(30000), isTrue);
    });

    test('shouldClear returns true when positionMs > durationMs - 10000', () {
      expect(ProgressDao.shouldClear(110001, 120000), isTrue);
      expect(ProgressDao.shouldClear(110000, 120000), isFalse);
      expect(ProgressDao.shouldClear(109999, 120000), isFalse);
      expect(ProgressDao.shouldClear(50000, 120000), isFalse);
    });

    test('shouldClear returns false when durationMs is null', () {
      expect(ProgressDao.shouldClear(999999, null), isFalse);
      expect(ProgressDao.shouldClear(0, null), isFalse);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // PRG-01 fix: 进度恢复对话框接入 (PRG-FIX-T01~T06)
  // ═══════════════════════════════════════════════════════════════════════════

  group('PRG-01 进度恢复对话框接入 (PRG-FIX-T01~T06)', () {
    late Database db;
    late ProgressDao dao;

    setUpAll(() {
      initSqfliteFfi();
    });

    setUp(() async {
      db = await openTestDatabase(TestSchema.progress);
      dao = ProgressDao();
      // FK 约束现对所有 schema 生效（BUG-16-S2）：progress 行须引用已存在的连接
      await seedConnection(db);
      await seedConnection(db, id: 2); // 跨连接隔离用例（PRG-T13 等）引用连接 2
    });

    tearDown(() async {
      await db.close();
    });

    // ── PRG-FIX-T01: 有进度文件 → 对话框 → 选择继续 → 从保存位置播放 ──────

    testWidgets(
        'PRG-FIX-T01: dialog choose continue → returns true with position',
        (WidgetTester tester) async {
      final progress = testProgress(
        positionMs: 120000, // 2:00
        durationMs: 240000,
      );

      bool? dialogResult;
      await tester.pumpWidget(
        ProviderScope(
          child: MaterialApp(
            home: Scaffold(
              body: Builder(
                builder: (context) {
                  return ElevatedButton(
                    onPressed: () async {
                      dialogResult = await showProgressResumeDialog(
                        context,
                        ProviderScope.containerOf(context),
                        progress,
                      );
                    },
                    child: const Text('Show'),
                  );
                },
              ),
            ),
          ),
        ),
      );

      await tester.tap(find.text('Show'));
      await tester.pumpAndSettle();

      // Dialog should be visible with progress position
      expect(find.text('恢复播放进度'), findsOneWidget);
      expect(find.textContaining('2:00'), findsOneWidget);

      // Tap "继续播放"
      await tester.tap(find.textContaining('继续播放'));
      await tester.pumpAndSettle();

      expect(dialogResult, isTrue,
          reason: '选择继续播放应返回 true，调用方应设置 startPositionMs');
    });

    // ── PRG-FIX-T02: 有进度文件 → 对话框 → 选择从头开始 → 从头播放 ──────

    testWidgets('PRG-FIX-T02: dialog choose start over → returns false',
        (WidgetTester tester) async {
      final progress = testProgress(positionMs: 60000, durationMs: 180000);

      bool? dialogResult;
      await tester.pumpWidget(
        ProviderScope(
          child: MaterialApp(
            home: Scaffold(
              body: Builder(
                builder: (context) {
                  return ElevatedButton(
                    onPressed: () async {
                      dialogResult = await showProgressResumeDialog(
                        context,
                        ProviderScope.containerOf(context),
                        progress,
                      );
                    },
                    child: const Text('Show'),
                  );
                },
              ),
            ),
          ),
        ),
      );

      await tester.tap(find.text('Show'));
      await tester.pumpAndSettle();

      // Tap "从头播放"
      await tester.tap(find.text('从头播放'));
      await tester.pumpAndSettle();

      expect(dialogResult, isFalse,
          reason: '选择从头播放应返回 false，调用方不设置 startPositionMs');
    });

    // ── PRG-FIX-T03: 有进度文件 → 倒计时归零 → 自动选择继续播放 ──────────

    test('PRG-FIX-T03: countdown expiry triggers auto-continue', () {
      fakeAsync((async) {
        final container = ProviderContainer();
        addTearDown(container.dispose);

        final notifier = container.read(progressResumeProvider.notifier);
        final progress = testProgress(positionMs: 120000);

        notifier.show(progress);
        expect(notifier.state!.countdownSeconds, equals(5));

        // Advance 5 seconds
        for (int i = 0; i < 5; i++) {
          async.elapse(const Duration(seconds: 1));
        }

        expect(notifier.state!.isExpired, isTrue,
            reason: '倒计时归零后 isExpired 应为 true，对话框应自动选择继续播放');
        expect(notifier.state!.countdownSeconds, equals(0));

        container.dispose();
      });
    });

    // ── PRG-FIX-T04: 无进度文件 → 不弹对话框 → 直接从头播放 ──────────────

    test('PRG-FIX-T04: null progress → no dialog → play from beginning',
        () async {
      // Verify: when no progress exists, the provider returns null
      final container = ProviderContainer(
        overrides: [
          progressDaoProvider.overrideWithValue(dao),
        ],
      );
      addTearDown(container.dispose);

      // progressForFileProvider queries the DAO — with empty DB it returns null
      final result = await container.read(
        progressForFileProvider((
          connectionId: 1,
          filePath: '/music/no_progress.mp3',
        )).future,
      );
      expect(result, isNull,
          reason: '无进度记录时 ProgressDao.find 返回 null → 不弹对话框 → 直接从头播放');
    });

    // ── PRG-FIX-T05: 播放单曲目点击 → 同样触发恢复对话框 ──────────────────

    test('PRG-FIX-T05: playlist track tap queries progress via DAO', () async {
      // Save progress for a file
      await dao.upsert(
        connectionId: 1,
        filePath: '/music/playlist_song.mp3',
        positionMs: 90000,
        durationMs: 300000,
      );

      final container = ProviderContainer(
        overrides: [
          progressDaoProvider.overrideWithValue(dao),
        ],
      );
      addTearDown(container.dispose);

      // progressForFileProvider queries by (connectionId, filePath)
      final progress = await container.read(
        progressForFileProvider((
          connectionId: 1,
          filePath: '/music/playlist_song.mp3',
        )).future,
      );

      expect(progress, isNotNull,
          reason: '播放单曲目有进度时 progressForFileProvider 应返回进度记录');
      expect(progress!.positionMs, equals(90000), reason: '应返回正确的 positionMs');
      expect(progress.positionMs >= 5000, isTrue,
          reason: 'positionMs >= 5000 时应触发恢复对话框');
    });

    // ── PRG-FIX-T06: 进度 positionMs < 5000 → 不弹对话框 ──────────────────

    test('PRG-FIX-T06: position < 5s → skip dialog → direct play', () async {
      // Save a progress with position < 5000
      // Note: DAO.upsert would skip this (shouldSave returns false),
      // but we insert directly to test the UI-layer threshold logic
      final progress = testProgress(
        connectionId: 1,
        filePath: '/music/brief.mp3',
        positionMs: 3000, // 3 seconds
        durationMs: 120000,
      );
      await dao.rawInsertForTest(progress);

      final container = ProviderContainer(
        overrides: [
          progressDaoProvider.overrideWithValue(dao),
        ],
      );
      addTearDown(container.dispose);

      final result = await container.read(
        progressForFileProvider((
          connectionId: 1,
          filePath: '/music/brief.mp3',
        )).future,
      );

      // The DAO still returns the record, but the UI checks positionMs >= 5000
      if (result != null) {
        expect(result.positionMs < 5000, isTrue,
            reason: '进度 positionMs < 5000 的情况下获取到记录本身没问题，'
                '但 onFileTap/onTrackTap 中的阈值检查应跳过对话框');
      }

      // Verify the threshold logic directly
      final shouldShowDialog = result != null && result.positionMs >= 5000;
      expect(shouldShowDialog, isFalse, reason: 'positionMs < 5000 时不应弹出恢复对话框');
    });

    // ── Additional: PlayQueue constructed with startPositionMs ───────────────

    test('PRG-FIX: PlayQueue carries startPositionMs when resuming', () {
      const files = [
        NasFile(path: '/music/a.mp3', name: 'a.mp3', isDirectory: false),
        NasFile(path: '/music/b.mp3', name: 'b.mp3', isDirectory: false),
      ];

      // Without resume → no startPositionMs
      final queueWithout = PlayQueue(files: files, currentIndex: 0);
      expect(queueWithout.startPositionMs, isNull,
          reason: '无进度恢复时 startPositionMs 应为 null');

      // With resume → startPositionMs set
      final queueWith = PlayQueue(
        files: files,
        currentIndex: 0,
        startPositionMs: 120000,
      );
      expect(queueWith.startPositionMs, equals(120000),
          reason: '恢复播放时 startPositionMs 应为保存的 positionMs');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // TST-02: 播放进度保存与恢复端到端链路 (TST-T07~T13)
  // ═══════════════════════════════════════════════════════════════════════════

  group('TST-02 播放进度保存与恢复端到端链路 (TST-T07~T13)', () {
    late Database db;
    late ProgressDao dao;

    setUpAll(() {
      initSqfliteFfi();
    });

    setUp(() async {
      db = await openTestDatabase(TestSchema.progress);
      dao = ProgressDao();
      // Insert a test connection so activeConnectionProvider can resolve it
      await db.insert('connections', {
        'name': 'test-conn',
        'url': 'http://192.168.1.1:8080',
        'username': 'admin',
        'password': 'pw-key',
        'base_path': '/music',
        'is_active': 1,
        'created_at': DateTime.now().millisecondsSinceEpoch,
        'updated_at': DateTime.now().millisecondsSinceEpoch,
      });
    });

    tearDown(() async {
      await db.close();
    });

    // ── Helpers ────────────────────────────────────────────────────────────

    ConnectionConfig testConn() => ConnectionConfig(
          id: 1,
          name: 'test-conn',
          url: 'http://192.168.1.1:8080',
          username: 'admin',
          basePath: '/music',
          isActive: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

    const testFile =
        NasFile(path: '/music/test.mp3', name: 'test.mp3', isDirectory: false);

    const fileA =
        NasFile(path: '/music/a.mp3', name: 'a.mp3', isDirectory: false);

    const fileB =
        NasFile(path: '/music/b.mp3', name: 'b.mp3', isDirectory: false);

    /// Creates a [ProviderContainer] pre-configured with mock audio player,
    /// active connection, and progress DAO.  Returns the container and a
    /// [MockAudioPlayer] so the test can control its state.
    (ProviderContainer, MockAudioPlayer) createContainer({
      PlayQueue? queue,
      void Function(int count)? onSaveCalled,
      bool stubLoadAndPlay = false,
    }) {
      final mockPlayer = MockAudioPlayer();
      when(mockPlayer.position).thenReturn(const Duration(seconds: 30));
      when(mockPlayer.duration).thenReturn(const Duration(minutes: 3));
      when(mockPlayer.playing).thenReturn(true);

      final q = queue ?? PlayQueue(files: [testFile], currentIndex: 0);

      final conn = testConn();

      final overrides = <Override>[
        progressDaoProvider.overrideWithValue(dao),
        audioPlayerProvider.overrideWithValue(mockPlayer),
        currentPlayQueueProvider.overrideWith((_) => q),
      ];

      // Override saveProgressProvider to use the test connection directly
      // (bypasses activeConnectionProvider which is a FutureProvider and
      // may not resolve synchronously in tests).
      overrides.add(saveProgressProvider.overrideWith((ref) {
        return () {
          final queue = ref.read(currentPlayQueueProvider);
          if (queue == null) return;
          final player = ref.read(audioPlayerProvider);
          ref.read(upsertProgressProvider)(
            connectionId: conn.id!,
            filePath: queue.current.path,
            positionMs: player.position.inMilliseconds,
            durationMs: player.duration?.inMilliseconds,
          );
        };
      }));

      // Override upsertProgressProvider to count calls and delegate to the DAO
      int saveCount = 0;
      overrides.add(upsertProgressProvider.overrideWith((ref) {
        return ({
          required int connectionId,
          required String filePath,
          required int positionMs,
          int? durationMs,
        }) async {
          saveCount++;
          onSaveCalled?.call(saveCount);
          await dao.upsert(
            connectionId: connectionId,
            filePath: filePath,
            positionMs: positionMs,
            durationMs: durationMs,
          );
          ref.invalidate(progressForFileProvider((
            connectionId: connectionId,
            filePath: filePath,
          )));
        };
      }));

      if (stubLoadAndPlay) {
        overrides.add(loadAndPlayProvider.overrideWith((_) {
          return () async => const TrackLoadResult.failed();
        }));
        overrides
            .add(playModeProvider.overrideWith((_) => PlayMode.sequential));
      }

      final container = ProviderContainer(overrides: overrides);
      return (container, mockPlayer);
    }

    // ── TST-T07: 10s period save ──────────────────────────────────────────

    test('TST-T07: 10s周期保存 — fake_async推进30s → 3次upsert调用', () {
      fakeAsync((async) {
        // Set up a minimal container that counts save calls without touching
        // the SQLite database (native FFI ops do not play well with fake_async).
        int saveCount = 0;

        final mockPlayer = MockAudioPlayer();
        when(mockPlayer.position).thenReturn(const Duration(seconds: 30));
        when(mockPlayer.duration).thenReturn(const Duration(minutes: 3));

        final queue = PlayQueue(files: [testFile], currentIndex: 0);

        final container = ProviderContainer(
          overrides: [
            audioPlayerProvider.overrideWithValue(mockPlayer),
            currentPlayQueueProvider.overrideWith((_) => queue),
            saveProgressProvider.overrideWith((ref) {
              return () {
                // Assert pre-conditions silently; skip DB write in fake zone
                final q = ref.read(currentPlayQueueProvider);
                if (q != null) {
                  saveCount++;
                }
              };
            }),
          ],
        );

        // Start periodic save — replicates _startAutoSaveProvider logic
        final timer = Timer.periodic(const Duration(seconds: 10), (_) {
          container.read(saveProgressProvider)();
        });

        // Advance 30 seconds: callbacks fire at t=10s, t=20s, t=30s
        async.elapse(const Duration(seconds: 30));

        expect(saveCount, equals(3),
            reason: '30秒内应有3次周期保存(t=10s, t=20s, t=30s)');

        timer.cancel();
        container.dispose();
      });
    });

    // ── TST-T08: Pause-triggered save ─────────────────────────────────────

    test('TST-T08: 暂停触发保存 — playerStateStream发出playing: true→false', () {
      final stateController =
          StreamController<PlayerState>.broadcast(sync: true);

      final mockPlayer = MockAudioPlayer();
      when(mockPlayer.playing).thenReturn(true);

      final queue = PlayQueue(files: [testFile], currentIndex: 0);

      int saveCount = 0;

      final container = ProviderContainer(
        overrides: [
          currentPlayQueueProvider.overrideWith((_) => queue),
          saveProgressProvider.overrideWith((ref) {
            return () {
              final q = ref.read(currentPlayQueueProvider);
              if (q != null) {
                saveCount++;
              }
            };
          }),
        ],
      );
      addTearDown(() async {
        await stateController.close();
        container.dispose();
      });

      // Replicate _startPauseSaveProvider logic — listen on the stream
      // directly rather than through the mock's getter to avoid Mockito
      // stubbing issues with Stream getters.
      var wasPlaying = mockPlayer.playing; // true (stubbed above)
      final sub = stateController.stream.listen((state) {
        final playing = state.playing;
        if (wasPlaying && !playing) {
          container.read(saveProgressProvider)();
        }
        wasPlaying = playing;
      });
      addTearDown(() async {
        await sub.cancel();
      });

      // Emit playing=true — no save triggered (no state change)
      stateController.add(PlayerState(true, ProcessingState.ready));

      // Emit playing=false — save should trigger
      stateController.add(PlayerState(false, ProcessingState.ready));
      expect(saveCount, equals(1), reason: 'playing→paused转换应触发进度保存');

      // Emit another playing→paused cycle — should trigger again
      stateController.add(PlayerState(true, ProcessingState.ready));
      stateController.add(PlayerState(false, ProcessingState.ready));
      expect(saveCount, equals(2), reason: '第二次playing→paused也应触发保存');

      // Consecutive paused states — should NOT trigger duplicate saves
      stateController.add(PlayerState(false, ProcessingState.ready));
      expect(saveCount, equals(2), reason: '连续paused状态不应触发重复保存');
    });

    // ── TST-T09: Save before skip ─────────────────────────────────────────

    test('TST-T09: 切歌前保存 — skipToNext调用前保存旧曲目进度', () async {
      String? savedFilePath;

      final queue = PlayQueue(files: [fileA, fileB], currentIndex: 0);
      final mockPlayer = MockAudioPlayer();
      when(mockPlayer.position).thenReturn(const Duration(seconds: 30));
      when(mockPlayer.duration).thenReturn(const Duration(minutes: 3));
      when(mockPlayer.playing).thenReturn(true);

      final conn = testConn();

      // Use late final so the upsertProgressProvider closure can reference
      // the container after it's been fully created.
      late final ProviderContainer container;
      container = ProviderContainer(
        overrides: [
          progressDaoProvider.overrideWithValue(dao),
          audioPlayerProvider.overrideWithValue(mockPlayer),
          activeConnectionProvider.overrideWith((_) => conn),
          currentPlayQueueProvider.overrideWith((_) => queue),
          playModeProvider.overrideWith((_) => PlayMode.sequential),
          loadAndPlayProvider.overrideWith((_) {
            return () async => const TrackLoadResult.failed();
          }),
          upsertProgressProvider.overrideWith((ref) {
            return ({
              required int connectionId,
              required String filePath,
              required int positionMs,
              int? durationMs,
            }) async {
              // Capture which file is being saved (before queue advances)
              final q = container.read(currentPlayQueueProvider);
              savedFilePath = q?.current.path;
              await dao.upsert(
                connectionId: connectionId,
                filePath: filePath,
                positionMs: positionMs,
                durationMs: durationMs,
              );
              ref.invalidate(progressForFileProvider((
                connectionId: connectionId,
                filePath: filePath,
              )));
            };
          }),
        ],
      );
      addTearDown(container.dispose);

      // Call skipToNext — this internally calls saveProgressProvider first,
      // THEN advances the queue and calls loadAndPlayProvider.
      await container.read(skipToNextProvider)();

      // Verify save was called with the OLD track (before queue advance)
      expect(savedFilePath, equals('/music/a.mp3'),
          reason: '切歌前应保存旧曲目 /music/a.mp3 的进度');

      // Verify queue advanced to next track
      final newQueue = container.read(currentPlayQueueProvider);
      expect(newQueue!.currentIndex, equals(1), reason: '队列应前进到下一首(index=1)');
      expect(newQueue.current.path, equals('/music/b.mp3'),
          reason: '当前曲目应为 b.mp3');

      // Verify the save actually reached the DAO
      final progress = await dao.find(1, '/music/a.mp3');
      expect(progress, isNotNull, reason: '旧曲目进度应已写入数据库');
      expect(progress!.positionMs, equals(30000),
          reason: '保存的positionMs应与mock player一致');
    });

    // ── TST-T10: Background save ──────────────────────────────────────────

    test('TST-T10: 进入后台保存 — AppLifecycleState.paused → 保存进度', () async {
      int saveCount = 0;
      final (container, _) = createContainer(
        onSaveCalled: (count) => saveCount = count,
      );
      addTearDown(container.dispose);

      // Simulate what PlayerScreen.didChangeAppLifecycleState does:
      // when AppLifecycleState.paused is received, call _saveProgress()
      container.read(saveProgressProvider)();

      expect(saveCount, equals(1), reason: '进入后台时应触发一次进度保存');

      // Verify data reached the DAO
      final progress = await dao.find(1, '/music/test.mp3');
      expect(progress, isNotNull, reason: '后台保存的进度应持久化到数据库');
      expect(progress!.positionMs, equals(30000),
          reason: '保存的positionMs应与mock player一致');
    });

    // ── TST-T11: Dispose save ─────────────────────────────────────────────

    test('TST-T11: dispose保存 — PlayerScreen dispose触发保存并清理订阅', () {
      fakeAsync((async) {
        int saveCount = 0;
        final (container, _) = createContainer(
          onSaveCalled: (count) => saveCount = count,
        );

        // Start periodic auto-save timer (what loadAndPlayProvider does)
        final timer = Timer.periodic(const Duration(seconds: 10), (_) {
          container.read(saveProgressProvider)();
        });

        // Simulate what PlayerScreen.dispose does:
        // 1. Save final progress
        container.read(saveProgressProvider)();
        expect(saveCount, equals(1), reason: 'dispose时应执行最后一次进度保存');

        // 2. Cancel auto-save subscriptions
        container.read(cancelPlaybackSubscriptionsProvider)();
        timer.cancel();

        // Advance time — no more saves should fire because timer is cancelled
        async.elapse(const Duration(seconds: 30));

        // Only the manual save, not the periodic ones (timer was cancelled)
        expect(saveCount, equals(1), reason: '取消订阅后不应再有周期保存');

        container.dispose();
      });
    });

    // ── TST-T12: Restart recovery ─────────────────────────────────────────

    test('TST-T12: 重启恢复 — 新ProviderContainer恢复进度和队列', () async {
      // ── Container 1: save progress ──────────────────────────────────
      final container1 = ProviderContainer(
        overrides: [
          progressDaoProvider.overrideWithValue(dao),
        ],
      );

      await dao.upsert(
        connectionId: 1,
        filePath: '/music/test.mp3',
        positionMs: 120000, // 2:00 into a track
        durationMs: 300000,
      );

      container1.dispose();

      // ── Container 2: simulate app restart ────────────────────────────
      final container2 = ProviderContainer(
        overrides: [
          progressDaoProvider.overrideWithValue(dao),
        ],
      );
      addTearDown(container2.dispose);

      // Read latest progress (as restoreStartupProgressProvider does)
      final latest = await container2.read(latestPlayedProgressProvider.future);
      expect(latest, isNotNull, reason: '重启后应能读取到上次保存的进度');
      expect(latest!.positionMs, equals(120000));
      expect(latest.filePath, equals('/music/test.mp3'));
      expect(latest.connectionId, equals(1));

      // ── Build restored queue ────────────────────────────────────────
      final restoredQueue = PlayQueue(
        files: [testFile],
        currentIndex: 0,
        startPositionMs: latest.positionMs,
      );
      expect(restoredQueue.startPositionMs, equals(120000),
          reason: '恢复的队列应携带保存的positionMs');

      // ── Verify: queue exists but does NOT auto-play ─────────────────
      // (Queue carries startPositionMs but the player layer decides whether
      // to actually start playing — restart should only restore position,
      // wait for user to tap play.)
      expect(restoredQueue.current.path, equals('/music/test.mp3'));

      // ── Test applyLatestProgressToQueue ─────────────────────────────
      final applied = applyLatestProgressToQueue(
        queue: PlayQueue(files: [testFile], currentIndex: 0),
        activeConnectionId: 1,
        latestProgress: latest,
      );
      expect(applied!.startPositionMs, equals(120000),
          reason: 'applyLatestProgressToQueue应设置startPositionMs');

      // Connection mismatch → no startPositionMs set
      final notApplied = applyLatestProgressToQueue(
        queue: PlayQueue(files: [testFile], currentIndex: 0),
        activeConnectionId: 999,
        latestProgress: latest,
      );
      expect(notApplied!.startPositionMs, isNull,
          reason: '连接ID不匹配时不设置startPositionMs');

      // File path mismatch → no startPositionMs set
      final fileMismatch = applyLatestProgressToQueue(
        queue: PlayQueue(files: [fileB], currentIndex: 0),
        activeConnectionId: 1,
        latestProgress: latest,
      );
      expect(fileMismatch!.startPositionMs, isNull,
          reason: '文件路径不匹配时不设置startPositionMs');

      // ── Test sanitizeResumePosition ─────────────────────────────────
      expect(sanitizeResumePosition(120000, 300000), equals(120000),
          reason: '合法位置不变');
      expect(sanitizeResumePosition(-1, 300000), equals(0), reason: '负数归零');
      expect(sanitizeResumePosition(300000, 300000), equals(0),
          reason: '到达结尾归零');
      expect(sanitizeResumePosition(350000, 300000), equals(0),
          reason: '超过时长归零');
    });

    // TST-T13（upsertLatest 物理删除）已于 2026-07-24 随 BUG-11 修复删除：
    // upsertLatest 属已废弃的单活跃记录模型死代码（生产零调用），
    // 用户裁决 play_progress 归属按文件多记录模型。
  });

  // ═════════════════════════════════════════════════════════════════════════════
  // TST-17: PRG-G02 short duration progress
  // ═════════════════════════════════════════════════════════════════════════════

  group('TST-17: PRG-G02 short duration progress', () {
    // TST-T138: durationMs <= 10000 的文件不自动清除
    // shouldClear returns false when file is very short,
    // because the 10-second "finished" window is meaningless.

    test('TST-T138: durationMs <= 10000 files are NOT auto-cleared', () {
      // shouldClear returns false when durationMs <= 10000 (G-3 rule)
      expect(ProgressDao.shouldClear(7990, 8000), isFalse,
          reason: 'TST-T138: 时长8s文件, positionMs接近结尾也不应清除');
      expect(ProgressDao.shouldClear(9000, 10000), isFalse,
          reason: 'TST-T138: 时长恰好10s文件, 不应清除');
      expect(ProgressDao.shouldClear(5000, 5000), isFalse,
          reason: 'TST-T138: 时长5s超短文件(<=10s), 不应清除');

      // For files > 10s, normal shouldClear logic applies
      expect(ProgressDao.shouldClear(95000, 100000), isTrue,
          reason: 'TST-T138: 时长100s文件, position在最后10s内应清除');
      expect(ProgressDao.shouldClear(85000, 100000), isFalse,
          reason: 'TST-T138: 时长100s文件, position在最后10s外不应清除');

      // shouldSave is independent: position < 5s always skipped
      expect(ProgressDao.shouldSave(4000), isFalse,
          reason: 'TST-T138: positionMs<5s 跳过保存');
      expect(ProgressDao.shouldSave(5000), isTrue,
          reason: 'TST-T138: positionMs>=5s 正常保存');
    });

    // TST-T148: startPositionMs 设置验证
    test('TST-T148: queue with startPositionMs carries position to player', () {
      final queue = PlayQueue(
        files: [
          const NasFile(
              name: 'song.mp3', path: '/music/song.mp3', isDirectory: false),
        ],
        currentIndex: 0,
        startPositionMs: 45000,
      );
      expect(queue.startPositionMs, equals(45000),
          reason: 'TST-T148: startPositionMs 应正确携带到队列');

      // withIndex preserves startPositionMs (caller must reset explicitly
      // if the index changes via user swipe, e.g. via withStartPosition(null))
      final sameIndex = queue.withIndex(0);
      expect(sameIndex.startPositionMs, equals(45000),
          reason: 'TST-T148: withIndex 保留 startPositionMs');

      // withStartPosition can clear it explicitly
      final cleared = queue.withStartPosition(null);
      expect(cleared.startPositionMs, isNull,
          reason: 'TST-T148: withStartPosition(null) 清除 startPositionMs');

      // withStartPosition can set a new value
      final set = queue.withStartPosition(30000);
      expect(set.startPositionMs, equals(30000),
          reason: 'TST-T148: withStartPosition 可设置新的 startPositionMs');
    });
  });

  // ═════════════════════════════════════════════════════════════════════════════
  // REF-02-S2: progressDaoProvider 类型为 IProgressDao（CTR4）
  // ═════════════════════════════════════════════════════════════════════════════

  group('REF-02-S2: progressDaoProvider 类型为 IProgressDao', () {
    test('REF-02-S2: 编译期声明 + 运行时契约断言', () {
      final container = ProviderContainer();
      addTearDown(container.dispose);

      // 编译期锚：provider 读取结果必须可赋给 IProgressDao。
      final IProgressDao dao = container.read(progressDaoProvider);
      expect(dao, isA<IProgressDao>(),
          reason: 'REF-02-S2: progressDaoProvider 必须暴露 IProgressDao 契约'
              '而非具体类类型');
    });

    test('REF-02-S2: 默认读取不触碰数据库（实例创建方式不变）', () {
      final container = ProviderContainer();
      addTearDown(container.dispose);

      final dao = container.read(progressDaoProvider);
      expect(dao, isNotNull, reason: 'REF-02-S2: progressDaoProvider 默认应返回实例');
    });
  });

  // ═════════════════════════════════════════════════════════════════════════════
  // REF-02-S9: IProgressDao 不含 rawInsert（CTR5）— 静态文本断言
  // ═════════════════════════════════════════════════════════════════════════════

  group('REF-02-S9: IProgressDao 不含 rawInsert', () {
    test('REF-02-S9: database_contract.dart 接口定义无 rawInsert', () {
      final file = File('lib/core/contracts/database_contract.dart');
      expect(file.existsSync(), isTrue,
          reason: '契约文件应存在 —— REF-02 实现未落地（预期失败）');
      expect(file.readAsStringSync(), isNot(contains('rawInsert')),
          reason: 'REF-02-S9: IProgressDao 不得保留 rawInsert 测试钩子'
              '（当前 database_contract.dart:67）');
    });

    test('REF-02-S9: progress_dao.dart 生产实现无 rawInsert', () {
      final file = File('lib/core/database/dao/progress_dao.dart');
      expect(file.existsSync(), isTrue,
          reason: 'progress_dao.dart 应存在 —— REF-02 实现未落地（预期失败）');
      expect(file.readAsStringSync(), isNot(contains('rawInsert')),
          reason: 'REF-02-S9: 生产 DAO 不得保留仅测试使用的 rawInsert 方法'
              '（当前 progress_dao.dart:78-83）');
    });
  });

  // ═════════════════════════════════════════════════════════════════════════════
  // TEST-05-S4: 两层路由栈关闭进度对话框 → 下层页面完整、无 double-pop
  // ═════════════════════════════════════════════════════════════════════════════

  group('TEST-05-S4 两层路由栈关闭进度对话框 (PRG9)', () {
    testWidgets('TEST-05-S4: 关闭对话框 → 下层页面仍在 + 对话框移除 + 无 double-pop',
        (WidgetTester tester) async {
      final progress = testProgress(positionMs: 30000, durationMs: 600000);

      // Given Navigator 栈为 [HomePage, BrowserPage]（下层页面在栈中）
      await tester.pumpWidget(
        ProviderScope(
          child: MaterialApp(
            home: Scaffold(
              body: Center(
                child: Builder(
                  builder: (context) => Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const Text('HomePage'),
                      ElevatedButton(
                        onPressed: () {
                          Navigator.of(context).push(
                            MaterialPageRoute<void>(
                              builder: (_) => Scaffold(
                                body: Center(
                                  child: Builder(
                                    builder: (dialogContext) => Column(
                                      mainAxisAlignment:
                                          MainAxisAlignment.center,
                                      children: [
                                        const Text('BrowserPage'),
                                        ElevatedButton(
                                          onPressed: () {
                                            showProgressResumeDialog(
                                              dialogContext,
                                              ProviderScope.containerOf(
                                                  dialogContext),
                                              progress,
                                            );
                                          },
                                          child: const Text('Show Dialog'),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          );
                        },
                        child: const Text('Open Browser'),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      );

      // 压入下层页面 → 栈 [HomePage, BrowserPage]
      await tester.tap(find.text('Open Browser'));
      await tester.pumpAndSettle();
      expect(find.text('BrowserPage'), findsOneWidget,
          reason: 'TEST-05-S4 前置：下层页面已压栈');

      // 打开进度对话框 → 栈 [HomePage, BrowserPage, Dialog]
      // 不用 pumpAndSettle：对话框有 5s 倒计时 Timer.periodic
      await tester.tap(find.text('Show Dialog'));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 100));
      expect(find.text('恢复播放进度'), findsOneWidget,
          reason: 'TEST-05-S4 前置：进度对话框已压栈');

      // When 用户关闭对话框（点"从头播放"）
      await tester.tap(find.text('从头播放'));
      await tester.pumpAndSettle();

      // Then 对话框 widget 已移除
      expect(find.text('恢复播放进度'), findsNothing,
          reason: 'TEST-05-S4: 关闭后对话框应从路由栈移除');

      // And 下层页面仍在栈中（未被 pop）
      expect(find.text('BrowserPage'), findsOneWidget,
          reason: 'TEST-05-S4: 关闭对话框不得把下层页面一并 pop');

      // 否定断言: 不弹出下层路由 / 不 double-pop——若多 pop 一层会回到 HomePage
      expect(find.text('HomePage'), findsNothing,
          reason: 'TEST-05-S4: 关闭对话框不得 double-pop 弹回下层之下的页面');

      // 否定断言: 不抛出 Navigator 操作异常
      expect(tester.takeException(), isNull,
          reason: 'TEST-05-S4: 关闭对话框不得抛出 Navigator 异常');
    });
  });
}
