#!/bin/bash
# Install git hooks for this clone.
#
# Creates a thin wrapper at .git/hooks/pre-push that delegates to the
# version-controlled scripts/hooks/pre-push, so hook updates are picked up
# automatically via `git pull` — no reinstall needed after the first run.
#
# Usage:  bash scripts/install-hooks.sh

set -e

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "error: not inside a git repository" >&2
  exit 1
}
HOOK_DIR="$(git rev-parse --git-path hooks)"

PRE_PUSH_HOOK="$REPO_ROOT/scripts/hooks/pre-push"
WRAPPER="$HOOK_DIR/pre-push"

if [ ! -f "$PRE_PUSH_HOOK" ]; then
  echo "error: $PRE_PUSH_HOOK not found. Run this from the repo root." >&2
  exit 1
fi

mkdir -p "$HOOK_DIR"

cat > "$WRAPPER" <<EOF
#!/bin/bash
# Auto-generated by scripts/install-hooks.sh — do not edit.
# Delegates to the version-controlled hook so updates land via git pull.
exec "\$(git rev-parse --show-toplevel)/scripts/hooks/pre-push" "\$@"
EOF
chmod +x "$WRAPPER"
chmod +x "$PRE_PUSH_HOOK"

echo "Installed pre-push hook:"
echo "  wrapper:  $WRAPPER"
echo "  delegates: $PRE_PUSH_HOOK"
echo ""
echo "To bypass in an emergency: SKIP_PRE_PUSH=1 git push"
