// Mocks generated by Mockito 5.4.6 from annotations
// in nas_audio_player/test/features/playlist/bug_04_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nas_audio_player/core/database/dao/playlist_dao.dart' as _i2;
import 'package:nas_audio_player/shared/models/playlist.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlaylistDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistDao extends _i1.Mock implements _i2.PlaylistDao {
  MockPlaylistDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertPlaylist(_i4.Playlist? playlist) => (super.noSuchMethod(
        Invocation.method(
          #insertPlaylist,
          [playlist],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Playlist>> findAllPlaylists() => (super.noSuchMethod(
        Invocation.method(
          #findAllPlaylists,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Playlist>>.value(<_i4.Playlist>[]),
      ) as _i3.Future<List<_i4.Playlist>>);

  @override
  _i3.Future<void> updatePlaylist(_i4.Playlist? playlist) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlaylist,
          [playlist],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deletePlaylist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePlaylist,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addTracks(List<_i4.PlaylistTrack>? tracks) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTracks,
          [tracks],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.PlaylistTrack>> findTracksForPlaylist(int? playlistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findTracksForPlaylist,
          [playlistId],
        ),
        returnValue:
            _i3.Future<List<_i4.PlaylistTrack>>.value(<_i4.PlaylistTrack>[]),
      ) as _i3.Future<List<_i4.PlaylistTrack>>);

  @override
  _i3.Future<void> removeTracks(List<int>? trackIds) => (super.noSuchMethod(
        Invocation.method(
          #removeTracks,
          [trackIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> trackExists(
    int? playlistId,
    String? filePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackExists,
          [
            playlistId,
            filePath,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> reorderTrack(
    int? playlistId,
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderTrack,
          [
            playlistId,
            oldIndex,
            newIndex,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
